/*
 * 	Copyright (C) 2015 Artificial Intelligence
 * 	Laboratory @ University of Udine.
 * 
 * 	This file is part of the Distiller-CORE library.
 * 
 * 	Distiller-CORE is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU Lesser General Public
 * 	License as published by the Free Software Foundation; either
 * 	version 2.1 of the License, or (at your option) any later version.
 *
 * 	Distiller-CORE is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * 	Lesser General Public License for more details.
 *
 * 	You should have received a copy of the GNU Lesser General Public
 * 	License along with this library; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * 	MA 02110-1301  USA or see <http://www.gnu.org/licenses/>.
 */
package it.uniud.ailab.dcore.annotation;

import java.net.URI;

/**
 *
 * @author Marco Basaldella
 */
public class InferenceAnnotation extends Annotation {
    
    /**
     * The concept inferred.
     */
    private final String concept;

    /**
     * The score associated to the concept.
     */
    private final double score;
    
    /**
     * The URI associated with the concept.
     */
    private final URI uri;
    
    /**
     * Instantiates the annotation.
     * 
     * @param annotator the annotator that generated the annotation.
     * @param concept the annotated concept.
     * @param score the score associated to the concept by the annotator.
     * @param uri the URI associated to the concept
     */
    public InferenceAnnotation(String annotator,String concept,
            double score,URI uri) {
        super(annotator);
        this.concept = concept;
        this.score = score;
        this.uri = uri;
    }
    
    /**
     * Gets the concept inferred by the annotator.
     * 
     * @return the concept.
     */
    public String getConcept() {
        return concept;
    }

    /**
     * Gets the score associated to the concept inferred.
     * 
     * @return the score generated by the annotator.
     */
    public double getScore() {
        return score;
    }
    
    /**
     * Gers the URI associated with the concept.
     * 
     * @return the URI associated with the concept.
     */
    public URI getUri() {
        return uri;
    }
}
